```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: "Exemplo de Stack simples com S3"

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: meu-primeiro-bucket-cloudformation
